services:
  app:
    environment:
      CUESCORE_PROVIDER: fake
      ENABLE_TEST_API: "true"
      ENABLE_TEST_ROUTES_IN_PRODUCTION: "true"
      ADMIN_UI_USERNAME: admin
      ADMIN_UI_PASSWORD: admin

  test:
    build:
      context: .
      dockerfile: .testcontainer/Dockerfile
    image: darts/test-runner:local
    depends_on:
      app:
        condition: service_healthy
    environment:
      PLAYWRIGHT_BASE_URL: http://app:3000
    volumes:
      - .:/app
      - ./.testcontainer/logs:/var/test-logs
    working_dir: /app
    command: ["all"]
