version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=darts-test
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: darts-db-test
