version: '3.8'
services:
  test-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    ports:
      - '5433:5432'
    volumes:
      - test-db-data:/var/lib/postgresql/data

volumes:
  test-db-data:
