services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
    environment:
      DATABASE_URL: "postgresql://testuser:testpass@postgres:5432/darts-test"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=darts-test
    ports:
      - '5434:5432'
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb:
